
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.RadioAction revertToSavedAction;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action cutAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action cdromAction;
	
	private global::Gtk.Action refreshAction;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Toolbar toolbar1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.CheckButton cbSquare;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.SpinButton spAlto;
	
	private global::Gtk.SpinButton spAncho;
	
	private global::Gtk.SpinButton spCant;
	
	private global::Gtk.SpinButton spColumns;
	
	private global::Gtk.SpinButton spHeight;
	
	private global::Gtk.SpinButton spSpaceX;
	
	private global::Gtk.SpinButton spSpaceY;
	
	private global::Gtk.SpinButton spWidth;
	
	private global::Gtk.Table table3;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.CheckButton cbPreview;
	
	private global::Gtk.HScale hscale1;
	
	private global::Gtk.DrawingArea drawingarea1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.revertToSavedAction = new global::Gtk.RadioAction ("revertToSavedAction", null, null, "gtk-revert-to-saved", 0);
		this.revertToSavedAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		w1.Add (this.revertToSavedAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.cutAction = new global::Gtk.Action ("cutAction", null, null, "gtk-cut");
		w1.Add (this.cutAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.cdromAction = new global::Gtk.Action ("cdromAction", null, null, "gtk-cdrom");
		w1.Add (this.cdromAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("IluCut Pro 0.1");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(9));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 3;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='openAction' action='openAction'/><toolitem name='cutAction' action='cutAction'/><toolitem name='cdromAction' action='cdromAction'/><toolitem name='refreshAction' action='refreshAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox2.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(10)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Llenar Hoja");
		this.table1.Add (this.button4);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.button4]));
		w3.TopAttach = ((uint)(4));
		w3.BottomAttach = ((uint)(5));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.cbSquare = new global::Gtk.CheckButton ();
		this.cbSquare.CanFocus = true;
		this.cbSquare.Name = "cbSquare";
		this.cbSquare.Label = "";
		this.cbSquare.DrawIndicator = true;
		this.cbSquare.UseUnderline = true;
		this.table1.Add (this.cbSquare);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbSquare]));
		w4.TopAttach = ((uint)(7));
		w4.BottomAttach = ((uint)(8));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Ancho ↔");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Encuadrado");
		this.table1.Add (this.label10);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
		w6.TopAttach = ((uint)(7));
		w6.BottomAttach = ((uint)(8));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Espaciado ↔");
		this.table1.Add (this.label12);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.label12]));
		w7.TopAttach = ((uint)(5));
		w7.BottomAttach = ((uint)(6));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Espaciado ↕");
		this.table1.Add (this.label13);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.label13]));
		w8.TopAttach = ((uint)(6));
		w8.BottomAttach = ((uint)(7));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Ancho papel");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w9.TopAttach = ((uint)(8));
		w9.BottomAttach = ((uint)(9));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Alto papel");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w10.TopAttach = ((uint)(9));
		w10.BottomAttach = ((uint)(10));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Cantidad");
		this.table1.Add (this.label7);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Columnas");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Alto ↕");
		this.table1.Add (this.label9);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spAlto = new global::Gtk.SpinButton (5, 5000, 1);
		this.spAlto.CanFocus = true;
		this.spAlto.Name = "spAlto";
		this.spAlto.Adjustment.PageIncrement = 10;
		this.spAlto.ClimbRate = 1;
		this.spAlto.Numeric = true;
		this.spAlto.Value = 297;
		this.table1.Add (this.spAlto);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.spAlto]));
		w14.TopAttach = ((uint)(9));
		w14.BottomAttach = ((uint)(10));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spAncho = new global::Gtk.SpinButton (5, 700, 1);
		this.spAncho.CanFocus = true;
		this.spAncho.Name = "spAncho";
		this.spAncho.Adjustment.PageIncrement = 10;
		this.spAncho.ClimbRate = 1;
		this.spAncho.Numeric = true;
		this.spAncho.Value = 210;
		this.table1.Add (this.spAncho);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.spAncho]));
		w15.TopAttach = ((uint)(8));
		w15.BottomAttach = ((uint)(9));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spCant = new global::Gtk.SpinButton (1, 999, 1);
		this.spCant.CanFocus = true;
		this.spCant.Name = "spCant";
		this.spCant.Adjustment.PageIncrement = 10;
		this.spCant.ClimbRate = 1;
		this.spCant.Numeric = true;
		this.spCant.Value = 1;
		this.table1.Add (this.spCant);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.spCant]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spColumns = new global::Gtk.SpinButton (1, 100, 1);
		this.spColumns.CanFocus = true;
		this.spColumns.Name = "spColumns";
		this.spColumns.Adjustment.PageIncrement = 10;
		this.spColumns.ClimbRate = 1;
		this.spColumns.Numeric = true;
		this.spColumns.Value = 1;
		this.table1.Add (this.spColumns);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.spColumns]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spHeight = new global::Gtk.SpinButton (1, 999999, 0.05);
		this.spHeight.CanFocus = true;
		this.spHeight.Name = "spHeight";
		this.spHeight.Adjustment.PageIncrement = 10;
		this.spHeight.ClimbRate = 1;
		this.spHeight.Numeric = true;
		this.spHeight.Value = 1;
		this.table1.Add (this.spHeight);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.spHeight]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spSpaceX = new global::Gtk.SpinButton (0, 100, 0.05);
		this.spSpaceX.CanFocus = true;
		this.spSpaceX.Name = "spSpaceX";
		this.spSpaceX.Adjustment.PageIncrement = 10;
		this.spSpaceX.ClimbRate = 1;
		this.spSpaceX.Numeric = true;
		this.spSpaceX.Value = 1;
		this.table1.Add (this.spSpaceX);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.spSpaceX]));
		w19.TopAttach = ((uint)(5));
		w19.BottomAttach = ((uint)(6));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spSpaceY = new global::Gtk.SpinButton (0, 100, 0.05);
		this.spSpaceY.CanFocus = true;
		this.spSpaceY.Name = "spSpaceY";
		this.spSpaceY.Adjustment.PageIncrement = 10;
		this.spSpaceY.ClimbRate = 1;
		this.spSpaceY.Numeric = true;
		this.spSpaceY.Value = 1;
		this.table1.Add (this.spSpaceY);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.spSpaceY]));
		w20.TopAttach = ((uint)(6));
		w20.BottomAttach = ((uint)(7));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spWidth = new global::Gtk.SpinButton (1, 999999, 0.05);
		this.spWidth.CanFocus = true;
		this.spWidth.Name = "spWidth";
		this.spWidth.Adjustment.PageIncrement = 10;
		this.spWidth.ClimbRate = 1;
		this.spWidth.Numeric = true;
		this.spWidth.Value = 1;
		this.table1.Add (this.spWidth);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.spWidth]));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 35;
		this.button1.HeightRequest = 35;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.table3.Add (this.button1);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.button1]));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 35;
		this.button2.HeightRequest = 35;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.table3.Add (this.button2);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.button2]));
		w23.LeftAttach = ((uint)(1));
		w23.RightAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add (this.table3);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.table3]));
		w24.TopAttach = ((uint)(4));
		w24.BottomAttach = ((uint)(5));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Auto");
		this.table2.Add (this.button3);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.button3]));
		w26.TopAttach = ((uint)(1));
		w26.BottomAttach = ((uint)(2));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.cbPreview = new global::Gtk.CheckButton ();
		this.cbPreview.CanFocus = true;
		this.cbPreview.Name = "cbPreview";
		this.cbPreview.Label = global::Mono.Unix.Catalog.GetString ("Vista previa");
		this.cbPreview.Active = true;
		this.cbPreview.DrawIndicator = true;
		this.cbPreview.UseUnderline = true;
		this.table2.Add (this.cbPreview);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbPreview]));
		w27.LeftAttach = ((uint)(1));
		w27.RightAttach = ((uint)(2));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hscale1 = new global::Gtk.HScale (null);
		this.hscale1.CanFocus = true;
		this.hscale1.Name = "hscale1";
		this.hscale1.Adjustment.Lower = 1;
		this.hscale1.Adjustment.Upper = 400;
		this.hscale1.Adjustment.PageIncrement = 10;
		this.hscale1.Adjustment.StepIncrement = 1;
		this.hscale1.Adjustment.Value = 186;
		this.hscale1.DrawValue = true;
		this.hscale1.Digits = 0;
		this.hscale1.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.hscale1);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.hscale1]));
		w28.TopAttach = ((uint)(1));
		w28.BottomAttach = ((uint)(2));
		w28.LeftAttach = ((uint)(1));
		w28.RightAttach = ((uint)(2));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table2);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table2]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.hbox3.Add (this.vbox2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox2]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.Name = "drawingarea1";
		this.hbox3.Add (this.drawingarea1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.drawingarea1]));
		w31.Position = 1;
		this.Add (this.hbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 576;
		this.DefaultHeight = 545;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.cdromAction.Activated += new global::System.EventHandler (this.OnCdromActionActivated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.button2.Pressed += new global::System.EventHandler (this.OnButton2Pressed);
		this.button1.Pressed += new global::System.EventHandler (this.OnButton1Pressed);
		this.spWidth.ValueChanged += new global::System.EventHandler (this.OnSpWidthValueChanged);
		this.spSpaceY.ValueChanged += new global::System.EventHandler (this.OnSpSpaceYValueChanged);
		this.spSpaceX.ValueChanged += new global::System.EventHandler (this.OnSpSpaceXValueChanged);
		this.spHeight.ValueChanged += new global::System.EventHandler (this.OnSpHeightValueChanged);
		this.spColumns.ValueChanged += new global::System.EventHandler (this.OnSpColumnsValueChanged);
		this.spCant.ValueChanged += new global::System.EventHandler (this.OnSpCantValueChanged);
		this.spAncho.ValueChanged += new global::System.EventHandler (this.OnSpAnchoValueChanged);
		this.spAlto.ValueChanged += new global::System.EventHandler (this.OnSpAltoValueChanged);
		this.button4.Pressed += new global::System.EventHandler (this.OnButton4Pressed);
		this.hscale1.ValueChanged += new global::System.EventHandler (this.OnHscale1ValueChanged);
		this.cbPreview.Toggled += new global::System.EventHandler (this.OnCbPreviewToggled);
		this.button3.Pressed += new global::System.EventHandler (this.OnButton3Pressed);
		this.drawingarea1.ExposeEvent += new global::Gtk.ExposeEventHandler (this.vistaPrevia);
	}
}
